# yaml-language-server: $schema=https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/bundled/config/document.vscode.json
# dsc.exe config --parameters-file 12-dscv3.parameters.yaml test -f 12-dscv3.config.dsc.yaml
# dsc.exe config set -f 12-dscv3.config.dsc.yaml
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
parameters: ## Parameters are used to pass values to the configuration
  ensureIIS: ## Parameter name
    type: string
    defaultValue: Present
    allowedValues: ## Allowed values for the parameter, whether we  want to install or not
      - Present
      - Absent
  ensureSQL:
    type: string
    defaultValue: Present
    allowedValues:
      - Present
      - Absent
resources:
## Install IIS
  - name: Use Windows PowerShell resources
    type: Microsoft.Windows/WindowsPowerShell
    properties:
      resources:
        - name: Web server install
          type: PSDesiredStateConfiguration/WindowsFeature
          properties:
            Name: Web-Server 
            IncludeAllSubFeature: True
            Ensure: "[parameters('ensureIIS')]"
## Install SQL Server 2022 Developer
  - name: Windows PowerShell                      
    type: Microsoft.DSC/Powershell                
    properties:                                   
      resources:                                  
      - name: Install SQL Server                   
        type: Microsoft.WinGet.DSC/WinGetPackage  
        properties:                               
          id: Microsoft.SQLServer.2022.Developer   ## Kept running into odd bugs with calling this like i did in 05-poshSQL.winget, failed back to standard install for now 
          source: winget
          Ensure: "[parameters('ensureSQL')]"                          